apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: python-dsa-gateway
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
    - port:
        number: 443
        name: https-cat-herding
        protocol: HTTPS
      hosts:
        - dsa.cat-herding.net
      tls:
        mode: SIMPLE
        credentialName: python-dsa-tls-cert
    - port:
        number: 443
        name: https-hugecat
        protocol: HTTPS
      hosts:
        - dsa.hugecat.net
        - hugecat.net
      tls:
        mode: SIMPLE
        credentialName: python-dsa-hugecat-tls-cert
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - dsa.cat-herding.net
        - dsa.hugecat.net
