apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use default namespace; cluster-scoped resources only.
# Remove explicit namespace to avoid creating a new one.

resources:
  - app.yaml
  - certificate-dsa-cat-herding.yaml
  - certificate-dsa-hugecat.yaml
  - gateway-default.yaml
  - virtualservice-default.yaml
  - virtualservice-hugecat-redirect.yaml
  - authorization-policy-ext-authz.yaml
