apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: python-dsa-virtualservice
spec:
  hosts:
    - dsa.cat-herding.net
    - dsa.hugecat.net
  gateways:
    - python-dsa-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: python-dsa
            port:
              number: 80
